spring:
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    url: jdbc:h2:mem:helpdesk
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties: 
      hibernate:
        format_sql: true

# Server base endpoint
server:
  servlet:
    context-path: /api/v1
