spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/helpdesk
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
      hibernate: format_sql=true
    show-sql: true

# Server base endpoint
server:
  servlet:
    context-path: /api/v1